################################# Default configuration ###################
# provide your domain here
baseURL = "https://whydontlibraries.brimwats.com/"
# theme
theme = "dot"
# site title
title = "Why Don't Libraries"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[menu.main]]
name = "contact"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "sections"
hasChildren = true

  [[menu.main]]
  parent = "sections"
  name = "Pan-GLAMS"
  url = "pan-glams"
  weight = 1

  [[menu.main]]
  parent = "sections"
  name = "Libraries"
  url = "Libraries"
  weight = 2

  [[menu.main]]
  parent = "sections"
  name = "Archives"
  url = "Archives"
  weight = 3

  [[menu.main]]
  parent = "sections"
  name = "Galleries & Museums"
  url = "galleries-museums"
  weight = 4

  [[menu.main]]
  parent = "sections"
  name = "Special Collections"
  url = "special-collections"
  weight = 5


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/brimwats"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/brimwats"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "Hugo Dot Theme © [gethugothemes](https://gethugothemes.com/), 2020. All other text is licensed for free by Brian M. Watson under [CC-BY](https://creativecommons.org/licenses/by/4.0/)."

# banner
[Languages.en.params.banner]
title = "Why don't libraries..."
subtitle = "Why don't they just...?"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Feel free to reach out to us via the contact form here or via twitter."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"